### PR TITLE
Removed TUSafariActivity. Added Freedom.

### PR DESCRIPTION
**Pull request by ArtSabintsev**
Hey Ryan,

A few weeks ago you expressed interest in replacing TUSafariActivity with [Freedom](https://github.com/ArtSabintsev/Freedom). I've gone ahead and done that and tested it (see screenshot). I had to make my own Github OAuth App and change some provisioning profile stuff to get the app up and running to test it, but I've reverted it in this PR.

I've edited:
- IssuesVC
- Info.plist (`LSApplicationQueriesSchemes`)

Everything else in here should be Pod changes.

No hard feelings if you have had a change of heart and no longer want this in the app.

)

Screenshot shows that my phone has Safari and Chrome installed. The extension also is primed to work with Firefox, Brave, and Dolphin.

### CODE REVIEW

**Comment by rnystrom** [comment]
Awesome! TBH I forgot. Will review + merge!

**Comment by ArtSabintsev** [comment]
Sounds good. Fixed the tiny merge conflict as well.

**Comment by heumn** [comment]
Looks like you have some new conflicts here @ArtSabintsev 😄

**Comment by ArtSabintsev** [comment]
Will take care of them soon!

**Comment by rnystrom** [comment]
@ArtSabintsev I'm actually backing out of this atm, right now things are working pretty well, soon as I get enough feedback to justify I'll reopen!

**Comment by ArtSabintsev** [comment]
No problem - sounds good.

**Pull request closed without merging**
